# Generated by Django 5.2.7 on 2025-10-31 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('height', models.IntegerField()),
                ('pressure', models.CharField(max_length=20)),
                ('glucose', models.DecimalField(decimal_places=1, max_digits=4)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
