# Generated by Django 5.2.7 on 2025-10-24 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО пациента')),
                ('height', models.IntegerField(verbose_name='Рост (см)')),
                ('pressure', models.CharField(max_length=20, verbose_name='Давление')),
                ('glucose', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Глюкоза')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('name', 'height', 'pressure', 'glucose', 'age')},
            },
        ),
    ]
